### ISSUE TITLE
IOS star rating prompt not showing 

### ISSUE THREAD

**Issue by mcalc001** [gogoout/nativescript-rater#11]
Hi, on IOS after you select "rate demo" on the initial pop up nothing happens. 
Ive checks on IOS emulators and device using the demo app supplied as well as my own angular app. 

Im using IOS version 13.3
nativescript - 6.5.0

Thanks

**Comment by gogoout** [comment]
Unpublished app can't be reviewed, if the dialog pop up, it should work fine once it's published.

**Comment by mcalc001** [comment]
Okay that makes sense, thanks!!
