### ISSUE TITLE
Unexpected behaviour on showRateDialog()

### ISSUE THREAD

**Issue by mcalc001** [gogoout/nativescript-rater#12]
Hi, when calling showRateDialog() on IOS 13.3 i am am being prompted by the dialog used for 〜 iOS 10.2 not the star rating dialog for iOS 10.3 〜.

When i set debug to true as shown below, then call showRateDialogIfMeetsConditions() the star rating dialog shows as expected.

appRater.init({
  showNeverButton: false,
  debugMode: true
});

I would expect showRateDialog() to prompt the star rating dialog ?

Thanks

**Comment by gogoout** [comment]
https://github.com/takecian/SwiftRater/issues/21

In short, native `SKStoreReviewController` has a limit.
