### ISSUE TITLE
Android string xml resources

### ISSUE THREAD

**Issue by FlawaCLV** [gogoout/nativescript-rater#3]
I can't figure out where to put the custom labels for Android.

Can someone give me the path and the filename?

**Comment by gogoout** [comment]
It should be some where like `App_Resources/Android/src/main/res/values/strings.xml`. In there you shall be able to see the app name already defined.

**Comment by gogoout** [comment]
Actually, if you can't find the xml, just create one at the path I mentioned above instead.
