### ISSUE TITLE
 DebugMode False, keeps showing review request every time.

### ISSUE THREAD

**Issue by szgozcan** [gogoout/nativescript-rater#4]
### Make sure to check the demo app(s) for sample usage 

 Demo runs without problem

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

I used both Android and IOS, emulator and real devices as well.

### Please, provide the following version numbers that your issue occurs with:

    tns version 6.1.2
      "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.1"
       }
      },
      "description": "NativeScript Application",
      "license": "SEE LICENSE IN <your-license-filename>",
      "repository": "<fill-your-repository-here>",
      "dependencies": {
        "nativescript-admob": "^4.0.0",
        "nativescript-audio-player": "^1.0.3",
        "nativescript-gif": "^4.0.2",
        "nativescript-image": "^2.2.5",
        "nativescript-local-notifications": "^4.0.1",
        "nativescript-rater": "^2.1.1",
        "nativescript-theme-core": "~1.0.6",
        "tns-core-modules": "~6.1.0"
      },
      "devDependencies": {
        "nativescript-dev-webpack": "~1.2.0"

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Demo runs without a problem and I integrated it to my app. As it is mentioned in the README. I get the review request every time pages loads. ( I trigger the   appRater.showRateDialog() on page load.)

I wanted to test the plugin by setting the debug mode to false. So I would check usesUntilPrompt (3) works or not. I was expecting that when the pages load I would not see review request until I launched the app 4th times. But whenever the pages loads review request page appears. Having this in released version would be a problem.

 So, will I have the similar issue with the released version?  Or is there a way to test configs? 

Thank you in advance.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by gogoout** [comment]
Use `appRater.showRateDialogIfMeetsConditions()` instead.

**Comment by szgozcan** [comment]
Thx for the reply.
Actually appRater.showRateDialogIfMeetsConditions() worked in simulators. Then I tested in test flight via appconnect center. but this time I get no request. Is it what it supposed to be? I mean if I go with appRater.showRateDialogIfMeetsConditions()  as it works in simulators will I face the same results as test flight? thx in advance

**Comment by gogoout** [comment]
I'm not sure about if the simulator will behave exactly the same as testflight version (My guess would be yes). But in your Testflight version all the counter (days, uses, significant use) will reset, so make sure the conditions all met when you call `showRateDialogIfMeetsConditions`.

**Comment by szgozcan** [comment]
Eventhough during testflight we didn't see get any request alert, the apprater works fine in release in App Store. Thx for the help. Now I will test in android as well.

**Comment by szgozcan** [comment]
Hi, I use showRateDialogIfMeetsConditions() and it works fine with iOS. but on Android I can't make it show on when it is on debug:false mode. I run both the Android and İOS simulators at the same time with same code but on debug false option only iOS responds positively, get no request review on Android. To test it I relaunch the app for 3-5 times. Need help and thank you in advance.

**Comment by gogoout** [comment]
What's your `daysUntilPrompt `

**Comment by szgozcan** [comment]
Thx for fast response,

So what I have on my start page (where request is triggered) is:

        var appRater = require("nativescript-rater").appRater;
        appRater.setDaysUntilPrompt(7)
        appRater.setUsesUntilPrompt(3)
        appRater.setSignificantUsesUntilPrompt(2)
        appRater.setShowLaterButton(true)
        appRater.setShowNeverButton(true)
        appRater.setDebugMode(false);
  
        function onLoaded () {
                appRater.showRateDialogIfMeetsConditions();
       }
      exports.onLoaded=onLoaded;


and my app.js is as follows:

      var appRater = require("nativescript-rater").appRater;
      appRater.init({
      debugMode:false
      });

On IOS simulators request pops up on the fourth launch but on android emulators and real device nothing happens. Thank you again

**Comment by gogoout** [comment]
The condition is combined with "and". So have you wait 7 days before open it?

**Comment by szgozcan** [comment]
I haven't waited for 7 days. But it works on iOS without waiting for 7 days. I will keep you informed after it passes 7 days on Android. Thx

**Comment by szgozcan** [comment]
Hi,
It works on android as daysUntilPrompt is defined. Thx.
