### ISSUE TITLE
Feature on iOS - Add app country code parameter due to iTunes lookup fail.

### ISSUE THREAD

**Issue by Sauvetonbio** [gogoout/nativescript-rater#8]
Hello,

There is an issue on iOS when the app is available in only one country. The iTunes lookup return an empty response.

Related issue : https://github.com/takecian/SwiftRater/issues/30

SwiftRater documentation : 
`SwiftRater.countryCode = "fr"`

Could you please add this parameter in the next version of this NS plugin ? Thank you.

**Comment by gogoout** [comment]
Hi, sorry for the late response. You can access to `SwiftRater` by `appRater.ios`.
So I think `appRater.ios.countryCode = "fr"` will just work!
