### ISSUE TITLE
topmost() is deprecated. Use Frame.topmost() instead

### ISSUE THREAD

**Issue by bbroereES** [gogoout/nativescript-rater#9]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both -> iOS
- iOS/Android versions -> All
- emulator or device. What type of device? -> All

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) -> All
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)-> 6.5.1
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) -> 6.5.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here) -> none

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1. add rater plugin
2. start iOS simulator
3. open rater -> a console warning appears

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

A pull request is coming any minute now :)

**Comment by gogoout** [comment]
published
